webtalk_init -webtalk_dir /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/CX204-LAB6.sim/sim_1/behav/xsim/xsim.dir/reg_file_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 24 08:29:55 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "662d0d13-652a-4853-ae2f-8d6770e6b406" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1357566399254df6bff8ed824f0c7762" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Linuxmint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 22" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1260P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1147.465 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3581653096 -regid "" -xml /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/CX204-LAB6.sim/sim_1/behav/xsim/xsim.dir/reg_file_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/CX204-LAB6.sim/sim_1/behav/xsim/xsim.dir/reg_file_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/CX204-LAB6.sim/sim_1/behav/xsim/xsim.dir/reg_file_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
