#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 24 05:49:46 PST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim inst_mem_tb_behav -key {Behavioral:sim_1:Functional:inst_mem_tb} -tclbatch inst_mem_tb.tcl -view /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/inst_mem_tb_behav.wcfg -log simulate.log"
xsim inst_mem_tb_behav -key {Behavioral:sim_1:Functional:inst_mem_tb} -tclbatch inst_mem_tb.tcl -view /home/cenema/Desktop/Xilinx_Projects/CX-204/CX-204-lab6/CX204-LAB6/CX204-LAB6/inst_mem_tb_behav.wcfg -log simulate.log

